
package com.G3M4E5.Redflix88.vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Roberto Londoño
 */
public class Ventana extends javax.swing.JFrame implements ActionListener{
    
    PanelUsuarios panelUsuarios = new PanelUsuarios();
    PanelPeliculas panelPeliculas = new PanelPeliculas();
    PanelSeries panelSeries = new PanelSeries();
    
    VideoTrailer trailer = new VideoTrailer();
    
    
                
    
    public Ventana() {
        //runSpring
        //Redflix88Application.runSpring();
        initComponents();
        /*capturando la resolución de mi monitor - Resolución = tamaño en terminos de pixeles*/
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        //establece en terminos de alto y ancho la resolución
        Dimension tamanoPantalla = miPantalla.getScreenSize();
        int alturaPantalla = tamanoPantalla.height;//solo para el alto
        int anchoPantalla = tamanoPantalla.width;//solo para el ancho
        /*localizando mi ventana en el centro*/
        setLocation(anchoPantalla/4, alturaPantalla/4);
        contenedor.add(panelUsuarios);
        deshabilitarBotones();
        
        /*objeto tipo imagen para un icono*/
        Image miIcono = miPantalla.getImage("src/main/java/com/G3M4E5/Redflix88/vista/Redflix88icono.png"); 
        setIconImage(miIcono);//estableciendo icono
                
        panelUsuarios.setVisible(true);
        panelPeliculas.setVisible(false);
        panelSeries.setVisible(false);
        
        btnUsuarios.addActionListener(this);
        btnPeliculas.addActionListener(this);
        btnSeries.addActionListener(this);
        
        
        
        
    }
    
    private void deshabilitarBotones() {
        if(panelUsuarios.isVisible()){
            btnUsuarios.setEnabled(false);
            btnSeries.setEnabled(true);
            btnPeliculas.setEnabled(true);
        }else if(panelPeliculas.isVisible()){
            btnUsuarios.setEnabled(true);
            btnSeries.setEnabled(true);
            btnPeliculas.setEnabled(false);
        }else if(panelSeries.isVisible()){
            btnUsuarios.setEnabled(true);            
            btnPeliculas.setEnabled(true);
            btnSeries.setEnabled(false);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnSeries = new javax.swing.JButton();
        redflix88 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Redflix - Equipo 5");

        contenedor.setPreferredSize(new java.awt.Dimension(855, 524));
        contenedor.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(0, 51, 102));
        panelMenu.setPreferredSize(new java.awt.Dimension(250, 524));

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPeliculas.setBackground(new java.awt.Color(255, 255, 255));
        btnPeliculas.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnPeliculas.setForeground(new java.awt.Color(0, 0, 0));
        btnPeliculas.setText("PELICULAS");
        btnPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeliculas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSeries.setBackground(new java.awt.Color(255, 255, 255));
        btnSeries.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnSeries.setForeground(new java.awt.Color(0, 0, 0));
        btnSeries.setText("SERIES");
        btnSeries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeries.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        redflix88.setFont(new java.awt.Font("Segoe Print", 1, 60)); // NOI18N
        redflix88.setForeground(new java.awt.Color(0, 255, 102));
        redflix88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redflix88.setText("FLIX");
        redflix88.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Segoe Print", 1, 60)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("RED");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(btnSeries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redflix88, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redflix88, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        contenedor.add(panelMenu, java.awt.BorderLayout.LINE_START);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSeries;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel contenedor;
    private java.awt.Label label1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel redflix88;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object evt = e.getSource();
        
        if(evt.equals(btnUsuarios)){
            panelPeliculas.setVisible(false);
            panelSeries.setVisible(false);
            panelUsuarios.setVisible(true);
            
            
            contenedor.add(panelUsuarios);
            contenedor.validate();
            deshabilitarBotones();
            
        }else if(evt.equals(btnPeliculas)){
            panelUsuarios.setVisible(false);
            panelSeries.setVisible(false);
            panelPeliculas.setVisible(true);
            
            contenedor.add(panelPeliculas);
            contenedor.validate();
            deshabilitarBotones();
        }else if(evt.equals(btnSeries)){
            panelUsuarios.setVisible(false);
            panelPeliculas.setVisible(false);
            panelSeries.setVisible(true);
            
            contenedor.add(panelSeries);
            contenedor.validate();
            deshabilitarBotones();
        }
    }
}
